# Generated by Django 4.1.1 on 2022-10-10 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0005_alter_cars_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('passport_number', models.IntegerField(unique=True, verbose_name='Номер паспорта')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('priority', models.IntegerField(verbose_name='Приоритет')),
                ('address_take', models.CharField(max_length=150, verbose_name='Адрес получения')),
                ('address_delivery', models.CharField(max_length=150, verbose_name='Адрес выдачи')),
                ('time', models.DateTimeField(verbose_name='Время выдачи')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.RemoveField(
            model_name='cars',
            name='drive',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='engine_type',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='gearbox',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='mileage',
        ),
        migrations.AddField(
            model_name='cars',
            name='useful_capacity',
            field=models.FloatField(default=0, verbose_name='Полезный объём'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brands',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Марка'),
        ),
        migrations.DeleteModel(
            name='Drives',
        ),
        migrations.DeleteModel(
            name='Engine_types',
        ),
        migrations.DeleteModel(
            name='Gearboxes',
        ),
        migrations.AddField(
            model_name='orders',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bmstu_lab.cars', verbose_name='Автомобиль id'),
        ),
        migrations.AddField(
            model_name='orders',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bmstu_lab.drivers', verbose_name='Водитель id'),
        ),
    ]
