# Generated by Django 4.1.1 on 2022-12-04 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0012_rename_useful_capacity_cars_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='driver',
        ),
        migrations.DeleteModel(
            name='Drivers',
        ),
    ]
