# Generated by Django 4.1.1 on 2022-12-04 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0014_users_orders_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='address_delivery',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='priority',
        ),
    ]
