# Generated by Django 4.1.1 on 2022-12-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0030_alter_orders_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date_create',
            field=models.DateTimeField(null=True, verbose_name='Время создания заказа'),
        ),
        migrations.AddField(
            model_name='orders',
            name='date_end',
            field=models.DateTimeField(null=True, verbose_name='Время завершения заказа'),
        ),
        migrations.AddField(
            model_name='orders',
            name='date_start',
            field=models.DateTimeField(null=True, verbose_name='Время начала выполнения заказа'),
        ),
    ]
