# Generated by Django 4.1.1 on 2022-10-09 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0002_cars_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name': 'Марка', 'verbose_name_plural': 'Марки'},
        ),
        migrations.AlterModelOptions(
            name='cars',
            options={'ordering': ['brand'], 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='drives',
            options={'verbose_name': 'Привод', 'verbose_name_plural': 'Приводы'},
        ),
        migrations.AlterModelOptions(
            name='engine_types',
            options={'verbose_name': 'Тип двигателя', 'verbose_name_plural': 'Типы двигателей'},
        ),
        migrations.AlterModelOptions(
            name='gearboxes',
            options={'verbose_name': 'Коробка передач', 'verbose_name_plural': 'Коробки передач'},
        ),
        migrations.AlterField(
            model_name='cars',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bmstu_lab.brands', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='drive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bmstu_lab.drives', verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='engine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bmstu_lab.engine_types', verbose_name='Тип двигателя'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='gearbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bmstu_lab.gearboxes', verbose_name='Корбка передач'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='mileage',
            field=models.IntegerField(verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='photo',
            field=models.ImageField(blank=True, upload_to='bmstu_lab/static/photo/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='gearboxes',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Коробка передач'),
        ),
    ]
