# Generated by Django 4.1.1 on 2022-10-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0006_drivers_orders_remove_cars_drive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='photo',
            field=models.BinaryField(blank=True, verbose_name='Фото'),
        ),
    ]
