# Generated by Django 4.1.1 on 2022-11-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0009_alter_cars_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='cars',
            name='payload',
            field=models.FloatField(default=0, verbose_name='Грузоподъемность'),
        ),
    ]
