# Generated by Django 4.1.1 on 2022-11-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0010_cars_description_cars_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='payload',
            field=models.FloatField(verbose_name='Грузоподъемность'),
        ),
    ]
