# Generated by Django 4.1.1 on 2022-11-20 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0011_alter_cars_description_alter_cars_payload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='useful_capacity',
            new_name='capacity',
        ),
    ]
