# Generated by Django 4.1.1 on 2022-12-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0016_users_groups_users_is_superuser_users_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='login',
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default=12345, max_length=20, unique=True, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
