# Generated by Django 4.1.1 on 2022-12-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0019_remove_orders_userprofile_orders_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isManager',
            field=models.BooleanField(default=0, verbose_name='является Менеджером'),
            preserve_default=False,
        ),
    ]
