# Generated by Django 4.1.1 on 2022-12-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0020_userprofile_ismanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='brand',
            field=models.CharField(max_length=150, verbose_name='Марка'),
        ),
        migrations.DeleteModel(
            name='Brands',
        ),
    ]
