# Generated by Django 4.1.1 on 2022-12-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0021_alter_cars_brand_delete_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
