# Generated by Django 4.1.1 on 2022-12-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0026_alter_orders_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='time',
            field=models.DateField(verbose_name='Время выдачи'),
        ),
    ]
