# Generated by Django 4.1.1 on 2022-12-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0031_orders_date_create_orders_date_end_orders_date_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='tempmail@gk.tu', max_length=50),
            preserve_default=False,
        ),
    ]
